# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RNCodePush' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for RNCodePush
  pod 'AppCenterReactNativeShared', '~> 1.1.0'
  pod 'AppCenter/Push', '~> 1.1.0'
  pod 'RNMobileCenterShared', '~> 0.11.2'
  pod 'MobileCenter/Analytics', '~> 0.14.1'

  

  target 'RNCodePushTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'RNCodePush-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for RNCodePush-tvOS

  target 'RNCodePush-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
